[package]
name = "grav1synth"
version = "0.1.0"
edition = "2021"
rust-version = "1.59.0"
license = "MIT"
repository = "https://gitlab.com/shssoichiro/grav1synth"
description = "Grain Synth analyzer and editor for AV1 files"
keywords = ["video", "multimedia", "av1"]
categories = ["multimedia", "multimedia:video", "multimedia:encoding"]

[dependencies]
anyhow = "1.0.55"
arrayvec = "0.7.2"
av-format = "0.4.0"
av-ivf = "0.3.0"
clap = { version = "3.2.6", features = ["derive"] }
nom = "7.1.0"
num_enum = "0.5.7"

[profile.release]
codegen-units = 1
lto = "thin"
