[package]
name = "grav1synth"
version = "0.1.0-alpha.3"
edition = "2021"
rust-version = "1.59.0"
license = "MIT"
repository = "https://git.bluefalcon.cc/soichiro/grav1synth"
description = "Grain Synth analyzer and editor for AV1 files"
keywords = ["video", "multimedia", "av1"]
categories = ["multimedia", "multimedia::video", "multimedia::encoding"]

[dependencies]
anyhow = "1.0.55"
arrayvec = "0.7.2"
clap = { version = "3.2.6", features = ["derive"] }
dialoguer = "0.10.1"
ffmpeg = { version = "5.0.3", default-features = false, features = [
    "format",
], package = "ffmpeg-next" }
nom = "7.1.0"
num-traits = "0.2.15"
num_enum = "0.5.7"
pretty_env_logger = "0.4.0"

[profile.release]
codegen-units = 1
lto = "thin"
