[package]
name = "grav1synth"
version = "0.1.0"
edition = "2021"
rust-version = "1.59.0"
license = "MIT"
repository = "https://gitlab.com/shssoichiro/grav1synth"
description = "Grain Synth analyzer and editor for AV1 files"
keywords = ["video", "multimedia", "av1"]
categories = ["multimedia", "multimedia:video", "multimedia:encoding"]

[dependencies]
anyhow = "1.0.55"
av-format = "0.3.1"
av-ivf = "0.2.3"
bitvec = { version = "1", default-features = false, features = ["alloc", "std"] }
clap = { version = "3.1.5", features = ["derive"] }
nom = "7.1.0"
num_enum = "0.5.7"

[profile.release]
codegen-units = 1
lto = "thin"
